export const TORRENTE_NOTIFICATION_PORT = 7933;
export const PAYFLUXO_LISTENING_PORT = 9003;
export const PAYFLUXO_EXTERNAL_PORT = 9003;
export const PORT_MAPPING_EXPIRATION = 0;

export const TORRENTE_SESSIONS_SAVE_FOLDER = '.torrente'

// Prod
// export const PAYFLUXO_USING_PORT = PAYFLUXO_EXTERNAL_PORT;

// Test
export const PAYFLUXO_USING_PORT = PAYFLUXO_LISTENING_PORT;
